### ISSUE TITLE
installable release version?

### ISSUE THREAD

**Issue by LittleEntity** [hsz/idea-latex#1]
Hello,

I would really love to use the plugin. Is it released as installable plugin somewhere?

cya

**Comment by hsz** [comment]
Sorry, it's the very alpha version. I'll continue the work when I'll have more time. However it'll be done.
Stay tuned.

**Comment by hsz** [comment]
@LittleEntity I've made a first very simple release. I'll be available in plugins repository as soon as they'll accept it.

Plugin's page: https://plugins.jetbrains.com/plugin/7660
