### ISSUE TITLE
First occurance of regular bracket () reports an error

### ISSUE THREAD

**Issue by blacktav** [hsz/idea-latex#11]
The first-time regular parentheses "( ... )" is used in a document triggers an error, provided the opening bracket is not the first character in a line.

After that brackets are fine

Error message follows:

```
LaTeXTokenType.,, LaTeXTokenType.:, LaTeXTokenType.ARGUMENT, LaTeXTokenType.CRLF, LaTeXTokenType.IDENTIFIER, LaTeXTokenType.SPECIAL, LaTeXTokenType.\\, LaTeXTokenType.\begin or LaTeXTokenType.\end expected, got '(' at line 14 
```

**Comment by ThiefMaster** [comment]
This bug still exists..
