### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by AnimeshSinha1309** [hsz/idea-latex#12]
It would be really great if there were menu options for typing in special characters like pi, sigma, etc. Actually the menu needs to be expanded a lot, would help the IntelliJ plugin compete with full LaTeX editors.

**Comment by AnimeshSinha1309** [comment]
Another thing, trying to do that myself, I see that mobi.hsz.idea.latex.LatexInstructions has been referenced but the class does not exist, and IntelliJ give an error, actually several errors. Am I making a mistake, could you please tell me what is going on?

**Comment by giesberge** [comment]
Whole process should be similar to https://github.com/hsz/idea-gitignore

You have to generate sources using BNF and JFlex rules.
