### ISSUE TITLE
Improved navigation

### ISSUE THREAD

**Issue by cozmic72** [hsz/idea-latex#13]
It would be great to be able to navigate LaTeX files like one does code:
- find usages of a (custom) command
- goto definition of a (custom) command or a package
- selection expansion: word <-> sentence <-> paragraph <-> (sub-) section <-> chapter
- move selection (cf. code -> move statement)

**Comment by hsz** [comment]
@cozmic72 Thank you for reporting !

Can you explain more those cases with user scenarios ?
First look of those features is promising, but I need more information about it.
