### ISSUE TITLE
"Empty element parsed"

### ISSUE THREAD

**Issue by melbings** [hsz/idea-latex#14]
I have the following LateX source:

``` latex
\section{Teaching Algorithms in Computer Science}
\label{sec:introduction-teaching_algorithms}
It is a good idea but it is hard, because ``most students (around 70\%) are intimidated when they take a basic algorithms course''~\cite{Kintali2012}.
```

I get the following error displayed on the white space after the word "students": "Empty element parsed in 'latexFile' at offset 153". Please see the attached screenshot: ![latex-phpstorm](https://cloud.githubusercontent.com/assets/15344864/10761539/24190b32-7cc2-11e5-8689-ad0d33e90e79.jpg)

**Comment by hsz** [comment]
@melbings Thank you for reporting.

This issue has been resolved with the 7d4c1f81404fb848d0f94f79768c0132e25f81b4 commit.
It will be available with the `v0.3` release.
