### ISSUE TITLE
No preview no export PDF

### ISSUE THREAD

**Issue by bkda** [hsz/idea-latex#16]
You should give usage

**Comment by christian-steinmeyer** [comment]
@TracyDa, I don't know whether this will help, but I was able to use [latexmk](https://www.ctan.org/pkg/latexmk/) for "live preview" on windows. If you have it installed (it should come with MIKTex and TexLive - try `latexmk -v` in a terminal), you can simply run `latexmk -pvc -pdf [tex-filename]` and it will watch for changes in any of the used src files and recompile the sufficient amount of times to generate a new pdf, including bibtex etc. 
You'll also need a PDF viewer that updates on file changes, e.g. [SumatraPDF](http://www.sumatrapdfreader.org/free-pdf-reader.html).
