### ISSUE TITLE
Shortcuts should work in all keyboard layouts.

### ISSUE THREAD

**Issue by Chushuhuch** [hsz/idea-latex#18]
Both IDEA specific (like Ctrl-Alt-s) and general (like Ctrl-c, Ctrl-z) don't work in Russian keyboard layout.

Ubuntu 14.04
IntelliJ IDEA 2016.1.1
Build #IC-145.597, built on March 29, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by hsz** [comment]
@Chushuhuch How is it connected to the LaTeX plugin ?

**Comment by Chushuhuch** [comment]
I'm sorry, I was sure it's working everywhere else. Please ignore.
