### ISSUE TITLE
Add support for spell checking

### ISSUE THREAD

**Issue by ghost** [hsz/idea-latex#20]
Spell checking does not work for .tex files in Idea 15.0.5 with idea-latex plugin. According to this post [http://stackoverflow.com/questions/12445117/intellij-idea-how-to-enable-spellchecking-for-custom-language-plugins] this feature must be explicitly supported by the plugin.

**Comment by CJ-Wright** [comment]
Yea, I would really appreciate this issue getting resolved.

**Comment by mitar** [comment]
Please!

**Comment by CJ-Wright** [comment]
Does this mean that there is now spell checking?

**Comment by hsz** [comment]
@CJ-Wright Spell checking has been implemented and will be released with the `v0.3` version.

CC: @pajurtom @mitar

**Comment by mitar** [comment]
0.3 version has not been released yet, no?
