### ISSUE TITLE
Code folding happens where it is not needed

### ISSUE THREAD

**Issue by existme** [hsz/idea-latex#21]
At several occasions I have a code that looks like this:

```
\subsection{title}
    \begin{itemize}
        \item item1
        \item item2
        \item \textbf{title} : content
        \item item4
        \item item5
     \end{itemize}
```

when you open a file containing a portion of text like above, it would be collapsed to something like this:

```
+  \subsection{title}                                        <-------+    Collapsed code
+    \begin{itemize}....  : content                          <-------+
          \item item4
          \item item5
     \end{itemize}

```

which is both unwanted and confusing.

![collapsed-sample](https://cloud.githubusercontent.com/assets/3057279/15270517/e53bfc90-1a22-11e6-90d6-9bcd3f855452.png)

**Comment by ianfp** [comment]
Furthermore, how do I disable Latex code folding entirely?

**Comment by jaesharp** [comment]
@existme did you find a solution to this issue? I've run into it as well and am considering fixing it by adding in the ability to disable folding entirely (a nuclear option, to be sure) per (@ianfp)'s comment.

**Comment by existme** [comment]
@justinlynn No. Unfortunately, I actually stopped documenting my stuff using Latex and switched to markdown because it's more portable.

**Comment by jaesharp** [comment]
@existme That's unfortunate but understandable if it works better for you.

@ianfp More generally, I've forked the idea-latex source and added in an option to disable code folding for LaTeX documents in the usual place. I'm testing locally and will submit a PR shortly.

EDIT: This branch is at <https://github.com/justinlynn/idea-latex/tree/upstream-feature/disable-code-folding-option> until it's baked enough to PR.
