### ISSUE TITLE
Syntax error on sub- and superscript argument (mathmode)

### ISSUE THREAD

**Issue by JcBernack** [hsz/idea-latex#25]
This plugin has problems with the sub- and superscript syntax in mathmode and displays a wrong syntax error when the argument is in braces `{}`. Without the braces it works just fine.

Example: `$a_{b}$` or `$a^{b}$`
Error: `Empty element parsed in 'latexFile' at offset 3. LaTeXTokenType.,, LaTeXTokenType.:, LaTeXTokenType.ARGUMENT, LaTeXTokenType.CRLF, LaTeXTokenType.IDENTIFIER, LaTeXTokenType.SPECIAL, LaTeXTokenType.\\ or LaTeXTokenType.\begin expected, got '{'.`

**Comment by karelin** [comment]
I've encountered something very similar with the command:
` \newcommand{\superscript}[1]{\ensuremath{^{\textrm{#1}}}}`
Unfortunately, don't know how to copy exact error message.
