### ISSUE TITLE
Latex syntax parser error

### ISSUE THREAD

**Issue by mxushakov** [hsz/idea-latex#3]
Thy syntax parser fails to recognize following proper Latex expression:

``` latex
Let $g \in L^{p'}(\Omega)$
```

![image](https://cloud.githubusercontent.com/assets/7523168/5953768/e1ab5102-a796-11e4-8bda-2f9769e4fe03.png)

**Comment by hsz** [comment]
@mxushakov Which version of plugin do you use ?

**Comment by mxushakov** [comment]
@hsz Sorry for the late reply. It was version 0.2 from plugin repository.
