### ISSUE TITLE
Switching focus between splitters does not work properly

### ISSUE THREAD

**Issue by gapag** [hsz/idea-latex#4]
IntelliJ version: 14.0.3
idea-latex version: 0.2

Suppose you have two splitters open in your editor.
One has a .tex file, the other a text/java file.

![jakub](https://cloud.githubusercontent.com/assets/3069948/6285908/c500ead6-b901-11e4-8e92-0b5b6227c461.png)

I assigned a key "K" to the IDEA action "Goto Next Splitter" to switch focus between splitters.

Pressing the key "K" changes focus indeed, but the cursor disappears when the focus goes to any .tex file when the idea-latex plugin is active. It is not possible to type anything.

To make the cursor become functional again one has to click on the opened .tex file, which defeats the purpose of having a key switching focus between splitters.

**Comment by gapag** [comment]
Now I cannot replicate the bug anymore. 
It kept happening the first three times I ran Intellij Idea with the Latex plugin.

**Comment by digizeph** [comment]
@gapag sounds like the plugin healed itself.

**Comment by gapag** [comment]
Not really :) I anyway found a way to reproduce the bug.
In short: I suspect that the culprit is the toolbar of the .tex files editor

**When the bug does appear:**
**1.** Open IntelliJ with the idea-latex plugin installed. You should have your editor already with a splitter as in the picture in the first post.
**2.** Open a file, e.g. File.java file on one splitter
**3.** Open a .tex file e.g. File.tex in another splitter
**4.** Try to use the GOTO Splitter key as described in my previous post. The focus changes but the cursor is unresponsibe in the splitter with File.tex. 
**When the bug does not appear:**
**5.** Restart intellij.
**6.** Now the GOTO splitter key works correctly. Note that the toolbar is not on the File.tex splitter anymore!
**How to reproduce the bug from here**
**7.** Open a File2.tex file that is not yet opened in the workspace. It has the toolbar and it captures the cursor like in point **4.**

the reason why it started working for me was that I had already opened after the third time all the files I needed in my workspace :)

**Comment by hsz** [comment]
@gapag Thank you for reporting.
Meanwhile I've abandoned `LatexFileEditor` implementation of the `Editor` - it resolved this problem.
The fix will be available with the next `v0.3` release.
