### ISSUE TITLE
Mathmode

### ISSUE THREAD

**Issue by physikerwelt** [hsz/idea-latex#5]
Is there an option to highlight mathmode e.g. `$E=mc^2$ or \begin{equation} .. \end{equation}` ?

**Comment by olegs** [comment]
Looking forward for the feature as well :+1:

**Comment by hsz** [comment]
@physikerwelt @olegs Thanks for the request (it's very important in this stage of the plugin!).

Can you explait it in more details ? This feature will be implemented for sure, but I need some user scenarios to do it well. :-)

**Comment by Wikunia** [comment]
I think it would be nice to have a different background color for inline mathematics like:
`in time $\mathcal{O}(n)$ for each path` and for explicit math like:

```
\begin{equation} 

\end{equation}
```
