### ISSUE TITLE
Allow CTRL+click on \input{} files

### ISSUE THREAD

**Issue by thePanz** [hsz/idea-latex#7]
Allow to navigate to included file by CTRL+Click on \include{} directive

**Comment by hsz** [comment]
@thePanz Thanks for reporting !

This feature will be available in the next release. 
The file reference is handled for `\input`, `\include` and `\includeonly` instructions.

**Comment by Chushuhuch** [comment]
How about also navigating to command definitions? And will Ctrl-B work?
