### ISSUE TITLE
Spell checker

### ISSUE THREAD

**Issue by djstrong** [hsz/idea-latex#8]
Spell checker would be helpful.

**Comment by athospg** [comment]
You can add dictionaries to IDEA, explained in here https://www.jetbrains.com/idea/help/spellchecking.html.
And you can use a dictionary like the ones in here http://www.winedt.org/Dict/

**Comment by djstrong** [comment]
Spell checker normally works in e.g. Ruby code and in tex files without installed your plugin, but after installation it doesn't. I think it is not related to dictionaries.

**Comment by lolnoob** [comment]
Is the spell checker working now with *.tex files? How can I update the plugin to not realised yet version 0.3? I could help to implement it with some guidlines (have never done any idea plugin but I can't be that hard, can it? :) ).

**Comment by snorberhuis** [comment]
I would also like to see spellchecking added. It should be fairly trivial seeing this post: http://stackoverflow.com/questions/12445117/intellij-idea-how-to-enable-spellchecking-for-custom-language-plugins

I might do it myself in the near future and make a PR. If I find time.

**Comment by hsz** [comment]
@djstrong Sorry for the delay, but I had no time to handle this plugin. Anyway - I'm back on track.

Spell checker support has been added and will be available with the next `v0.3` release.

**Comment by christian-steinmeyer** [comment]
Hi @hsz , any idea on when `v0.3` will be released? If it still takes a while, maybe a `v.0.2.1` release would be an option. Looks like you've added quite a few things that would all be nice to have!

**Comment by EricWF** [comment]
@hsz: Is there a way to manually install the newest plugin against CLion? It only ships v2.0.
